const dummyInputOne = [
    ['e4', 'e5'],
    ['Nf3', 'Nc6'],
    ['Bc4', 'Bc5'],
    ['b4', 'Bxb4'],
    ['c3', 'Bc5'],
    ['O-O', 'd6'],
    ['d4', 'exd4'],
    ['cxd4', 'Bb6'],
    ['Nc3', 'Na5'],
    ['Bd3', 'Ne7'],
    ['e5', 'dxe5'],
    ['dxe5', 'O-O'],
    ['Qc2', 'h6'],
    ['Ba3', 'c5'],
    ['Rad1', 'Bd7'],
    ['e6', 'fxe6'],
    ['Bh7', 'Kh8'],
    ['Ne5', 'Nd5'],
    ['Nxd5', 'exd5'],
    ['Rxd5', 'Bf5'],
    ['Rxd8', 'Bxc2'],
    ['Rxf8', 'Rxf8'],
    ['Bxc2', null]
];

const dummyInputTwo = [
    ['e4', 'e5'],
    ['Nf3', 'Nc6'],
    ['Bc4', 'Bc5'],
    ['b4', 'Bxb4'],
    ['c3', 'Bc5'],
    ['O-O', 'd6'],
    ['d4', 'exd4'],
    ['cxd4', 'Bb6'],
    ['Bb2', 'Nf6'],
    ['d5', 'Na5'],
    ['Bd3', 'O-O'],
    ['Nc3', 'Bg4'],
    ['Ne2', 'Bxf3'],
    ['gxf3', 'c5'],
    ['Qd2', 'c4'],
    ['Bc2', 'Rc8'],
    ['Bc3', 'Rc5'],
    ['Kh1', 'Ne8'],
    ['Rg1', 'f6'],
    ['Nf4', 'Nc7'],
    ['Nh5', 'Rf7'],
    ['Qh6', 'Qf8'],
    ['Ba4', 'Kh8'],
    ['Bxf6', null]
];

const dummyCheckmate = [
    ['e4', 'c5'],
    ['Nf3', 'Nc6'],
    ['Bb5', 'g6'],
    ['Bxc6', 'dxc6'],
    ['d3', 'Bg7'],
    ['h3', 'Nf6'],
    ['Nc3', 'O-O'],
    ['Be3', 'b6'],
    ['Qd2', 'e5'],
    ['Bh6', 'Qd6'],
    ['O-O-O', 'a5'],
    ['g4', 'a4'],
    ['Kb1', 'Be6'],
    ['Ne2', 'b5'],
    ['Ng3', 'Rfd8'],
    ['Bxg7', 'Kxg7'],
    ['Qg5', 'Nd7'],
    ['Nf5', 'Bxf5'],
    ['gxf5', 'a3'],
    ['b3', 'h6'],
    ['Qg3', 'Kh7'],
    ['Rhg1', 'Qf6'],
    ['h4', 'gxf5'],
    ['Qh3', 'f4'],
    ['Rg5', 'Qe6'],
    ['Rf5', 'Rg8'],
    ['Ng5', 'hxg5'],
    ['Rxf7', 'Qxf7'],
    ['hxg5', 'Kg7'],
    [ 'Qh6', null] 
];

const dummyFalseEnPassant = [
    ['e4', 'e6'],
    ['d4', 'd5'],
    ['e5', 'c5'],
    ['c3', 'cxd4'],
    ['cxd4', 'Bb4'],
    ['Nc3', 'Nc6'],
    ['Nf3', 'Nge7'],
    ['Bd3', 'O-O'],
    ['Bxh7', 'Kxh7'],
    ['Ng5', 'Kg6'],
    ['h4', 'Nxd4'],
    ['Qg4', 'f5'],
    ['h5', 'Kh6'],
    ['Nxe6', 'g5'],
    ['hxg6', null]
];

const dummyEnPassant = [
    ['e4', 'e6'], 
    ['e5', 'd5'], 
    ['exd6', 'Bxd6'], 
    ['d4', 'Ne7'], 
    ['Bd3', 'Ng6'], 
    ['Nf3', 'Nc6'],
    ['Nc3', 'Nb4'], 
    ['Bc4', 'c6'], 
    ['Ne4', 'Bc7'], 
    ['O-O', 'O-O'], 
    ['Re1', 'Nd5'],
    ['Nc5', 'Nh4'], 
    ['Ne5', 'Nf5'], 
    ['c3', 'Bxe5'], 
    ['Rxe5', 'Nf6'], 
    ['Re1', 'h6'],
    ['Qf3', 'Nd5'], 
    ['Bb3', 'b6'], 
    ['Nd3', 'Ba6'], 
    ['Ne5', 'Rc8'], 
    ['Bc2', 'Nfe7'],
    ['Qg3', 'Kh8'], 
    ['Qh4', 'Kg8'], 
    ['Qg3', 'Kh8'], 
    ['Qh3', 'Ng8'], 
    ['Qh5', 'Rc7'],
    ['Bd2', 'Ndf6'], 
    ['Qh3', 'Nd5'], 
    ['c4', 'Ndf6'], 
    ['Rad1', 'Qe8'], 
    ['Bf4', 'Rc8'],
    ['Qa3', 'Bb7'], 
    ['Qxa7', 'Ba8'], 
    ['Qxb6', 'g5'], 
    ['Bg3', 'Nd7'], 
    ['Qb3', 'f5'],
    ['f3', 'Kg7'], 
    ['c5', 'Ndf6'], 
    ['Nc4', null]
];

const dummyPawnPromotion = [
    ['e4', 'c6'], 
    ['Nc3', 'd5'], 
    ['Nf3', 'Bg4'], 
    ['h3', 'Bxf3'], 
    ['Qxf3', 'Nf6'], 
    ['d3', 'e6'],
    ['g3', 'Bb4'], 
    ['Bd2', 'd4'], 
    ['Nb1', 'Bxd2'], 
    ['Nxd2', 'e5'], 
    ['Bg2', 'c5'],
    ['O-O', 'Nc6'], 
    ['Qe2', 'Qe7'], 
    ['f4', 'O-O-O'], 
    ['a3', 'Ne8'], 
    ['b4', 'cxb4'],
    ['Nc4', 'f6'], 
    ['fxe5', 'fxe5'], 
    ['axb4', 'Nc7'], 
    ['Na5', 'Nb5'], 
    ['Nxc6', 'bxc6'], 
    ['Rf2', 'g6'], 
    ['h4', 'Kb7'], 
    ['h5', 'Qxb4'], 
    ['Rf7', 'Kb6'], 
    ['Qf2', 'a5'],
    ['c4', 'Nc3'], 
    ['Rf1', 'a4'], 
    ['Qf6', 'Qc5'], 
    ['Rxh7', 'Rdf8'], 
    ['Qxg6', 'Rxh7'],
    ['Qxh7', 'Rxf1'], 
    ['Bxf1', 'a3'], 
    ['h6', 'a2'], 
    ['Qg8', 'a1=Q'], 
    ['h7', 'Qd6'],
    ['h8=Q', 'Qa7'], 
    ['g4', 'Kc5'], 
    ['Qf8', 'Qae7'], 
    ['Qa8', 'Kb4'], 
    ['Qh2', 'Kb3'],
    ['Qa1', 'Qa3'], 
    ['Qxa3', 'Kxa3'], 
    ['Qh6', 'Qf7'], 
    ['Kg2', 'Kb3'], 
    ['Qd2', 'Qh7'],
    ['Kg3', 'Qxe4'], 
    ['Qf2', 'Qh1'],
]

const dummyMoves = {
    dummyInputOne,
    dummyInputTwo,
    dummyCheckmate,
    dummyFalseEnPassant,
    dummyEnPassant,
    dummyPawnPromotion
};

module.exports = {dummyMoves};